version: '3.9'
services:
  registry:
    build:
      context: .
      args:
        - BASE=ubuntu
        - UBUNTU_VERSION=22.04
#        - BASE=alpine
#        - ALPINE_VERSION=3.16
        - REGISTRY_VERSION=2.8.1
        - UID=1000
        - GID=1000
      target: deploy
    container_name: registry
    ports:
      - '5000:5000'
    volumes:
      - registry/config:/etc/registry
      - registry/data:/var/lib/registry